model:
  model_id: dcae
  sample_size: [256,256]
  channels: 3
  latent_size: 16
  latent_channels: 64

  ch_0: 192
  ch_max: 1536

  encoder_blocks_per_stage: [1, 1, 1, 1, 1]
  decoder_blocks_per_stage: [2, 2, 2, 2, 2]

  use_middle_block: false
  skip_logvar: true

  discriminator:
    model_id: patchgan
    channels: 3
    ch_0: 128
    sample_size: [256, 256]

train:
  trainer_id: distill_dec
  data_id: local_cod_features
  data_kwargs:
    root_dir: [/mnt/data/waypoint_1/normalized360/MKIF/videos, /mnt/data/datasets/cod_yt_latents]
    mix_ratios: [0.95, 0.05]
    include_suffixes: [rgb]
    target_size: [512, 512]

  target_batch_size: 128
  batch_size: 16

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-15

  lpips_type: convnext
  loss_weights:
    l2: 1.0
    lpips: 12.0
    gan: 0.5
    r12: 0.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 1500
    min_lr: 1.0e-5

  delay_adv: 5000
  warmup_adv: 2000

  checkpoint_dir: checkpoints/waypoint_1_gan_dec_distill_patchgan
  teacher_ckpt: checkpoints/waypoint_1_f32c64_8res_rgb_only/step_385000.pt
  teacher_cfg: configs/waypoint_1/rgb_only.yml

  #encoder_cfg: configs/waypoint_1/rgb_enc_distill.yml
  #encoder_ckpt: wp1_vae_enc_distill.pt

  resume_ckpt: checkpoints/waypoint_1_gan_dec_distill_patchgan/step_5000.pt

  sample_interval: 1000
  save_interval: 5000

  latent_shift: 0
  latent_scale: 1

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: waypoint_1_gan_dec (patchgan, delay disc)
