model:
  model_id: dcae
  sample_size: [512,512]
  channels: 3
  latent_size: 16
  latent_channels: 64

  ch_0: 256
  ch_max: 2048

  encoder_blocks_per_stage: [1, 1, 1, 1, 1]
  decoder_blocks_per_stage: [1, 1, 1, 1, 1]

  use_middle_block: false
  skip_logvar: true

train:
  trainer_id: distill_enc
  data_id: local_cod_features
  data_kwargs:
    root_dir: [/mnt/data/waypoint_1/normalized360/MKIF/videos, /mnt/data/datasets/cod_yt_latents]
    mix_ratios: [0.95, 0.05]
    include_suffixes: [rgb]
    target_size: [512, 512]

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 2.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-15

  lpips_type: convnext
  loss_weights:
    l2: 1.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 1500
    min_lr: 1.0e-5

  checkpoint_dir: checkpoints/waypoint_1_f32c64_8res_rgb_only_distill_enc
  teacher_ckpt: checkpoints/waypoint_1_f32c64_8res_rgb_only/step_385000.pt
  teacher_cfg: configs/waypoint_1/rgb_only.yml
  resume_ckpt: null

  sample_interval: 1000
  save_interval: 5000

  latent_shift: 0
  latent_scale: 1

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: waypoint_1_rgb_enc_dist
