model:
  model_id: diff_dec
  sample_size: [16,16]
  channels: 32
  latent_size: 8
  latent_channels: 128
  patch_size: 1

  n_layers: 28
  n_heads: 24
  d_model: 1536

  causal: false
  mimetic_init: false
  block_size: null
  backbone: dit
  rope_impl: image+latent
  dropout: 0.0

train:
  trainer_id: diff_dec
  data_id: s3_cod_features
  data_kwargs:
    bucket_name: 1x-frames
    prefix: depth-and-rgb
    include_depth: true
    target_size: [512, 512]

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-15

  scheduler: null

  checkpoint_dir: checkpoints/diffdec_1x

  sample_interval: 1000
  save_interval: 10000

  teacher_ckpt: checkpoints/1x_rgb_depth/step_100000.pt
  teacher_cfg: configs/1x/base.yml

  latent_scale: 0.54
  ldm_scale: 0.4552
  sampling_steps: 20
  vae_size: [512,512]
  vae_id: dcae

wandb:
  name: ${env:WANDB_USER_NAME}
  project: new_vaes
  run_name: diffdec_1x
